import test from 'node:test';
import assert from 'node:assert/strict';
import {ATTACK_AT_IMPACT_CONTENT,ATTACK_AT_IMPACT_CUES} from '../academy-attack-at-impact-content.js';
import {countCueWords,validateAcademyCueSet} from '../academy-voice-manifest.js';

test('experience identity, owned alias and no-prerequisite mastery are exact',()=>{assert.equal(ATTACK_AT_IMPACT_CONTENT.experienceId,'attack-at-impact');assert.equal(ATTACK_AT_IMPACT_CONTENT.title,'Up or Down at Impact');assert.deepEqual(ATTACK_AT_IMPACT_CONTENT.conceptIds,['attack-angle']);assert.deepEqual(ATTACK_AT_IMPACT_CONTENT.prerequisiteExperienceIds,[]);assert.equal(ATTACK_AT_IMPACT_CONTENT.surfaces.length,6);});
test('five mastery tasks require four knowledge checks plus live geometry',()=>{assert.equal(ATTACK_AT_IMPACT_CONTENT.masteryTasks.length,5);assert.equal(ATTACK_AT_IMPACT_CONTENT.masteryTasks.filter(x=>x.kind==='choice').length,4);assert.equal(ATTACK_AT_IMPACT_CONTENT.masteryTasks.at(-1).mandatory,true);assert.match(ATTACK_AT_IMPACT_CONTENT.masteryTasks.at(-1).prompt,/impact marker/i);});
test('content separates tangent, face, launch, contact and universal targets',()=>{const text=JSON.stringify(ATTACK_AT_IMPACT_CONTENT);for(const phrase of['DIRECTION AT IMPACT','OUTCOME-LEVEL ANGLE LAB','MODEL GEOMETRY · FIXED PLANE','This is a rigid-circle model, not a club measurement.','DOMINANT DIRECT ANGULAR SENSITIVITY','SMALLER DIRECT MODIFIER'])assert.ok(text.includes(phrase),phrase);for(const forbidden of['negative means bad','compression score','Attack equals launch','hit down to','hit up to','four times more important'])assert.doesNotMatch(text,new RegExp(forbidden,'i'));});
test('all information sheets preserve source and model boundaries',()=>{assert.deepEqual(Object.keys(ATTACK_AT_IMPACT_CONTENT.sheets),['attack','loft','launch','influence','geometry','limits','sources']);assert.match(ATTACK_AT_IMPACT_CONTENT.sheets.limits.body,/phone has not observed your club/i);assert.match(ATTACK_AT_IMPACT_CONTENT.sheets.geometry.body,/vertical depth.*does not change/i);});
test('seven stable voice cues stay inside shared word and target contracts',()=>{const report=validateAcademyCueSet(ATTACK_AT_IMPACT_CUES);assert.equal(report.valid,true);assert.equal(report.ownerId,'attack-at-impact');assert.equal(ATTACK_AT_IMPACT_CUES.cues.length,7);for(const cue of ATTACK_AT_IMPACT_CUES.cues){assert.ok(countCueWords(cue.text)>=12&&countCueWords(cue.text)<=24);assert.ok(cue.beats[0].targetId.startsWith('attack-'));}});
test('myths and influence copy retain exact current-engine claims',()=>{const text=JSON.stringify(ATTACK_AT_IMPACT_CONTENT);assert.match(text,/Spin Loft falls 4°; Launch Angle rises 1°/);assert.match(text,/does not, by itself, tell launch, contact quality, or the correct target/);assert.match(text,/Descending means turf first/);assert.match(text,/Not from Attack Angle alone/);});
