import test from'node:test';import assert from'node:assert/strict';
import{solveFlight}from'../impact-flight.js';
import{evaluateEqualBallSpeedTransfer,SPEED_TRANSFER_FIXTURES as F,solveSpeedTransferState}from'../academy-speed-transfer-model.js';
const close=(actual,expected,tolerance=1e-9)=>assert.ok(Math.abs(actual-expected)<=tolerance,`${actual} != ${expected}`);

test('five primary fixtures retain exact protected Smash Ball Speed Carry and Backspin truth',()=>{
  const expected=[[1.328,106.24,148.86,6223.653549],[1.328,119.52,172.40,7001.610243089],[1.328,132.8,193.95,7779.566936766],[1.36,122.4,177.30,5432.971491363],[1.28,115.2,164.88,9000]];
  F.primary.forEach((input,index)=>{const state=solveSpeedTransferState(input),engine=solveFlight({clubSpeed:input.clubSpeed,dynamicLoft:input.spinLoft,attackAngle:0,faceAngle:0,clubPath:0,club:'7iron'});for(const key of['ballSpeed','carry','backspin'])assert.equal(state[key],engine[key]);close(state.smash,expected[index][0]);close(state.ballSpeed,expected[index][1]);close(state.carry,expected[index][2],.01);close(state.backspin,expected[index][3],.1);});
});

test('equal-output fixture produces exactly 130.56 mph through different raw transfers',()=>{const[a,b]=F.equal.map(solveSpeedTransferState);close(a.smash,1.36);close(b.smash,1.28);close(a.ballSpeed,130.56);close(b.ballSpeed,130.56);assert.notEqual(a.signature,b.signature);});
test('upper and lower model clamps expose raw value and model-limit state',()=>{const upper=solveSpeedTransferState(F.clamps[0]),below=solveSpeedTransferState({clubSpeed:90,spinLoft:9}),lower=solveSpeedTransferState(F.clamps[1]),beyond=solveSpeedTransferState({clubSpeed:90,spinLoft:80});close(upper.smash,1.42);assert.equal(upper.smashClamp,'upper');close(below.smash,1.42);assert.ok(below.smashRaw>below.smash);close(lower.smash,1.15);assert.equal(lower.smashClamp,'lower');close(beyond.smash,1.15);assert.ok(beyond.smashRaw<below.smashRaw);});
test('live evaluator requires every independent raw threshold compare and approved inference',()=>{const base={stateAInput:F.equal[0],stateBInput:F.equal[1],stateAInteracted:true,stateBInteracted:true,compareOpened:true,inferenceSelected:'ball-speed-alone-does-not-reveal-delivery'};const result=evaluateEqualBallSpeedTransfer(base);assert.equal(result.passed,true);assert.equal(result.clubSpeedGap,6);assert.equal(result.spinLoftGap,20);close(result.smashGap,.08);assert.equal(result.ballSpeedGap,0);for(const patch of[{stateAInteracted:false},{stateBInteracted:false},{compareOpened:false},{inferenceSelected:'delivery-revealed'},{presetInjected:true},{stateBInput:F.equal[0]},{stateBInput:{clubSpeed:101,spinLoft:45}},{stateBInput:{clubSpeed:102,spinLoft:40}},{stateBInput:{clubSpeed:112,spinLoft:77.5}}])assert.equal(evaluateEqualBallSpeedTransfer({...base,...patch}).passed,false,JSON.stringify(patch));});
test('non-finite zero and out-of-range values fail closed without readout or credit',()=>{for(const input of[{clubSpeed:0},{clubSpeed:NaN},{spinLoft:Infinity},{spinLoft:90},{club:'driver'}])assert.throws(()=>solveSpeedTransferState(input));assert.equal(evaluateEqualBallSpeedTransfer({}).passed,false);});
