import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {createRequire} from 'node:module';
import {readFile} from 'node:fs';
import {dirname,extname,resolve,sep} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createAcademySeed} from '../academy-store.js';

const require=createRequire(import.meta.url),{chromium,webkit}=require('../tools/node_modules/playwright-core');
const ROOT=resolve(dirname(fileURLToPath(import.meta.url)),'..'),WEBKIT=process.env.FG_ENGINE==='webkit'||process.argv.includes('--project=webkit');
const mime=file=>({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.woff2':'font/woff2'}[extname(file)]||'application/octet-stream');
let server,browser,baseUrl;
test.before(async()=>{server=createServer((request,response)=>{const path=decodeURIComponent(new URL(request.url,'http://127.0.0.1').pathname).replace(/^\/+/, '')||'index.html',file=resolve(ROOT,path),prefix=`${ROOT}${sep}`.toLowerCase();if(!`${file}${sep}`.toLowerCase().startsWith(prefix)){response.writeHead(403).end();return;}readFile(file,(error,data)=>{if(error){response.writeHead(404).end();return;}response.writeHead(200,{'Content-Type':mime(file),'Cache-Control':'no-store'});response.end(data);});});await new Promise((ok,fail)=>{server.once('error',fail);server.listen(0,'127.0.0.1',ok);});baseUrl=`http://127.0.0.1:${server.address().port}`;browser=WEBKIT?await webkit.launch({headless:true}):await chromium.launch({channel:'msedge',headless:true}).catch(()=>chromium.launch({channel:'chrome',headless:true}));});
test.after(async()=>{await browser?.close();await new Promise(ok=>server?.close(ok));});

function masteredStartLine(seed){const item=seed.experiences['start-line'];item.acceptedAttemptId='seed:start-line';item.masteredAt='2026-07-15T10:00:00Z';item.evidence.knowledgeBestCorrect=5;item.evidence.knowledgeTotal=5;item.evidence.liveTransferPassed=true;item.evidence.liveTransferEvidence={fixtureId:'seed'};return seed;}
function masterySeed({xp=0}={}){const seed=masteredStartLine(createAcademySeed()),item=seed.experiences.shape;seed.xp=xp;item.surface=4;item.unlockedSurfaces=[0,1,2,3,4];item.startedAt='2026-07-15T10:00:00Z';item.evidence.shape={lab:{stage:3,rightBuilt:true,leftBuilt:true,reflection:0},influence:{gapAnswer:0,speeds:[70,110],ampAnswer:0},myths:[true,true,true],mythAnswers:[1,1,1],masteryAnswers:[null,null,null,null],masteryIndex:0,attemptNumber:0};return seed;}
async function open(hash='#/experience/shape',viewport={width:430,height:932},seed=null){const context=await browser.newContext({viewport,deviceScaleFactor:1,reducedMotion:'no-preference'}),page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(`pageerror: ${error.message}`));page.on('console',message=>{if(message.type()==='error')errors.push(`console: ${message.text()}`);});if(seed)await page.addInitScript(value=>{if(!localStorage.getItem('strikearc.academy.v1'))localStorage.setItem('strikearc.academy.v1',JSON.stringify(value));},seed);await page.goto(`${baseUrl}/academy.html${hash}`,{waitUntil:'networkidle'});return{context,page,errors};}
const setRange=(page,selector,value)=>page.locator(selector).evaluate((input,next)=>{input.value=String(next);input.dispatchEvent(new Event('input',{bubbles:true}));},value);
async function answerKnowledge(page,answers){for(let i=0;i<4;i+=1){await page.locator(`[data-mastery-answer="${answers[i]}"]`).click();await page.locator('[data-action="next"]').click();}}

test('Shape preview and both legacy concepts share one renderer and correct sheets',async()=>{const{context,page,errors}=await open();assert.equal(await page.locator('#shapeExperience').count(),1);assert.match(await page.locator('.shape__prereq').textContent(),/PREVIEW/);for(const[concept,title]of[['spin-axis','Spin Axis'],['curve','Curve']]){await page.evaluate(id=>{location.hash=`#/lesson/${id}`;},concept);await page.locator('[data-sheet-title]').filter({hasText:title}).waitFor();assert.equal((await page.locator('[data-sheet-title]').textContent()).trim(),title);await page.locator('[data-sheet-close]').click();}assert.deepEqual(errors,[]);await context.close();});

test('S0–S3 prove same-start opposite shapes, Carry amplifier and honest boundary',async()=>{const{context,page,errors}=await open('#/experience/shape/surface/0',{width:430,height:932},masteredStartLine(createAcademySeed()));const lesson=page.locator('#shapeExperience');await lesson.locator('[data-shape-primary]').click();await lesson.locator('[data-lab-prediction="0"]').click();await setRange(page,'#shapeFace',2);await setRange(page,'#shapePath',-2);assert.equal(await lesson.getAttribute('data-surface'),'1');assert.match(await lesson.locator('.shape__alternative').textContent(),/\+1\.0° · RIGHT/);assert.match(await lesson.locator('.shape__alternative').textContent(),/\+9\.6 yd · RIGHT/);assert.equal(await lesson.locator('[data-voice-target="shape-curve-bracket"]').count(),1);assert.equal(await lesson.locator('[data-offline-bracket],[data-target-relative-endpoint]').count(),0);await setRange(page,'#shapeFace',0);await setRange(page,'#shapePath',4);await lesson.locator('[data-lab-reflection="0"]').click();await lesson.locator('[data-action="next"]').click();assert.equal(await lesson.getAttribute('data-surface'),'2');await lesson.locator('[data-gap-answer="0"]').click();await lesson.locator('[data-shape-speed="70"]').click();assert.match(await lesson.locator('.shape__alternative').textContent(),/\+6\.3° · RIGHT/);assert.match(await lesson.locator('.shape__alternative').textContent(),/\+4\.3 yd · RIGHT/);await lesson.locator('[data-shape-speed="110"]').click();assert.match(await lesson.locator('.shape__alternative').textContent(),/\+16\.2 yd · RIGHT/);await lesson.locator('[data-amp-answer="0"]').click();await lesson.locator('[data-action="next"]').click();for(const answer of[1,1,1]){await lesson.locator(`[data-myth-answer="${answer}"]`).click();await lesson.locator('[data-action="next"]').click();}assert.equal(await lesson.getAttribute('data-surface'),'4');const metrics=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,minTarget:Math.min(...[...document.querySelectorAll('#shapeExperience button,#shapeExperience input')].filter(el=>el.offsetParent).map(el=>el.getBoundingClientRect().height))}));assert.equal(metrics.overflow,false);assert.ok(metrics.minTarget>=44);assert.deepEqual(errors,[]);await context.close();});

test('4/5 without two-shape transfer remains Practiced and awards no XP',async()=>{const{context,page,errors}=await open('#/experience/shape/surface/4',{width:430,height:932},masterySeed({xp:20}));await answerKnowledge(page,[0,0,0,0]);await page.locator('[data-transfer-finish]').click();assert.match(await page.locator('[data-result-status]').textContent(),/another pass/);const stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('strikearc.academy.v1')));assert.equal(stored.xp,20);assert.equal(stored.experiences.shape.status,'practiced');assert.equal(stored.experiences.shape.evidence.knowledgeBestCorrect,4);assert.equal(stored.experiences.shape.evidence.liveTransferPassed,false);assert.deepEqual(errors,[]);await context.close();});

test('raw same-start near miss stays blocked; valid left then right capture masters once',async()=>{const{context,page,errors}=await open('#/experience/shape/surface/4',{width:375,height:812},masterySeed({xp:20}));await answerKnowledge(page,[0,0,0,1]);await setRange(page,'[data-transfer-face]',.14);await setRange(page,'[data-transfer-path]',4);assert.match(await page.locator('.shape__alternative').textContent(),/\+1\.1° · RIGHT/);assert.equal(await page.locator('[data-transfer-capture]').isDisabled(),true);await setRange(page,'[data-transfer-face]',0);await page.locator('[data-transfer-capture]').click();assert.equal(await page.locator('[data-transfer-phase]').getAttribute('data-transfer-phase'),'right');await setRange(page,'[data-transfer-face]',2);await setRange(page,'[data-transfer-path]',-2);await page.locator('[data-transfer-capture]').click();assert.equal((await page.locator('[data-result-status]').textContent()).trim(),'You separated start from bend.');let stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('strikearc.academy.v1')));assert.equal(stored.xp,140);assert.equal(stored.experiences.shape.status,'mastered');assert.equal(stored.experiences.shape.evidence.knowledgeBestCorrect,4);assert.equal(stored.experiences.shape.evidence.liveTransferEvidence.leftLaunchPassed,true);assert.equal(stored.experiences.shape.evidence.liveTransferEvidence.rightCurvePassed,true);await page.reload({waitUntil:'networkidle'});stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('strikearc.academy.v1')));assert.equal(stored.xp,140);assert.equal((await page.locator('[data-result-status]').textContent()).trim(),'You separated start from bend.');assert.deepEqual(errors,[]);await context.close();});
