import test from'node:test';import assert from'node:assert/strict';import{createServer}from'node:http';import{createRequire}from'node:module';import{readFile}from'node:fs';import{dirname,extname,resolve,sep}from'node:path';import{fileURLToPath}from'node:url';import{createAcademySeed}from'../academy-store.js';
const require=createRequire(import.meta.url),{chromium,webkit}=require('../tools/node_modules/playwright-core'),ROOT=resolve(dirname(fileURLToPath(import.meta.url)),'..'),WEBKIT=process.env.FG_ENGINE==='webkit'||process.argv.includes('--project=webkit'),mime=file=>({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.woff2':'font/woff2'}[extname(file)]||'application/octet-stream');let server,browser,baseUrl;
test.before(async()=>{server=createServer((request,response)=>{const path=decodeURIComponent(new URL(request.url,'http://x').pathname).replace(/^\/+/, '')||'index.html',file=resolve(ROOT,path),prefix=`${ROOT}${sep}`.toLowerCase();if(!`${file}${sep}`.toLowerCase().startsWith(prefix)){response.writeHead(403).end();return;}readFile(file,(error,data)=>{if(error){response.writeHead(404).end();return;}response.writeHead(200,{'Content-Type':mime(file),'Cache-Control':'no-store'});response.end(data);});});await new Promise((ok,fail)=>{server.once('error',fail);server.listen(0,'127.0.0.1',ok);});baseUrl=`http://127.0.0.1:${server.address().port}`;browser=WEBKIT?await webkit.launch({headless:true}):await chromium.launch({channel:'msedge',headless:true}).catch(()=>chromium.launch({channel:'chrome',headless:true}));});
test.after(async()=>{await browser?.close();await new Promise(ok=>server?.close(ok));});
function masterySeed({xp=0}={}){const seed=createAcademySeed();seed.xp=xp;const state=seed.experiences['speed-transfer'];state.surface=4;state.unlockedSurfaces=[0,1,2,3,4];state.startedAt='2026-07-15T10:00:00Z';return seed;}
async function open(hash='#/experience/speed-transfer',viewport={width:430,height:932},seed=null,reducedMotion='no-preference'){const context=await browser.newContext({viewport,deviceScaleFactor:1,reducedMotion}),page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(`pageerror: ${error.message}`));page.on('console',message=>{if(message.type()==='error')errors.push(`console: ${message.text()}`);});if(seed)await page.addInitScript(value=>{if(!localStorage.getItem('strikearc.academy.v1'))localStorage.setItem('strikearc.academy.v1',JSON.stringify(value));},seed);await page.goto(`${baseUrl}/academy.html${hash}`,{waitUntil:'networkidle'});return{context,page,errors};}
const setRange=(page,field,value)=>page.locator(`[data-live-field="${field}"]`).evaluate((element,next)=>{element.value=String(next);element.dispatchEvent(new Event('input',{bubbles:true}));},value);
async function answerMastery(page,answers=[1,2,1,2]){for(let index=0;index<4;index++){await page.locator(`[data-mastery-answer="${answers[index]}"]`).click();await page.locator('[data-action="next"]').click();}}

test('canonical and all three legacy aliases use one native Speed Transfer renderer',async()=>{const{context,page,errors}=await open();assert.equal(await page.locator('#speedTransferExperience').count(),1);assert.equal((await page.locator('h1').textContent()).trim(),'Different transfers. One outcome.');assert.match(await page.locator('.speed-transfer__ledger').textContent(),/CLUB.*RATIO.*BALL.*130\.56 mph/s);for(const[alias,title]of[['club-speed','Club Speed'],['smash','Smash Factor'],['ball-speed','Ball Speed']]){await page.evaluate(value=>location.hash=`#/lesson/${value}`,alias);await page.locator('[data-sheet-title]').filter({hasText:title}).waitFor();await page.locator('[data-sheet-close]').click();}assert.deepEqual(errors,[]);await context.close();});

test('S0–S3 prove definitions multiplication equal output clamp and collision boundary',async()=>{const{context,page,errors}=await open('#/experience/speed-transfer',{width:430,height:932},null,'reduce');const lesson=page.locator('#speedTransferExperience');await lesson.locator('[data-primary]').click();const answers=[0,2,1,0,0];for(let index=0;index<5;index++){await lesson.locator(`[data-lab-step="${index}"]`).click();await lesson.locator(`[data-lab-answer="${answers[index]}"]`).click();}assert.match(await lesson.textContent(),/MEASURED SPEEDS \+ MODELED RATIO VERIFIED/);await lesson.locator('[data-action="next"]').click();for(const stage of['multiply','speed','ratio','equal','ports'])await lesson.locator(`[data-influence="${stage}"]`).click();assert.match(await lesson.textContent(),/MODEL LIMIT REACHED.*RAW 1\.420.*IMPACT LOCATION.*NOT MODELED/s);await lesson.locator('[data-action="next"]').click();for(let index=0;index<5;index++){await lesson.locator('[data-myth-answer="1"]').click();await lesson.locator('[data-action="next"]').click();}assert.equal(await lesson.getAttribute('data-surface'),'4');const metrics=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,min:Math.min(...[...document.querySelectorAll('#speedTransferExperience button,#speedTransferExperience input')].filter(element=>element.offsetParent).map(element=>element.getBoundingClientRect().height))}));assert.equal(metrics.overflow,false);assert.ok(metrics.min>=44);assert.deepEqual(errors,[]);await context.close();});

test('perfect knowledge without compare-backed live pair remains Practiced',async()=>{const{context,page,errors}=await open('#/experience/speed-transfer/surface/4',{width:430,height:932},masterySeed({xp:20}));await answerMastery(page);await page.locator('[data-finish]').click();assert.match(await page.locator('[data-result-status]').textContent(),/needs repair/);const stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('strikearc.academy.v1')));assert.equal(stored.xp,20);assert.equal(stored.experiences['speed-transfer'].status,'practiced');assert.equal(stored.experiences['speed-transfer'].evidence.knowledgeBestCorrect,4);assert.deepEqual(errors,[]);await context.close();});

test('two learner-created equal-output transfers earn one canonical reward and raw evidence',async()=>{const{context,page,errors}=await open('#/experience/speed-transfer/surface/4',{width:375,height:812},masterySeed({xp:20}));await answerMastery(page);for(const[field,value]of Object.entries({clubSpeed:96,spinLoft:25}))await setRange(page,field,value);assert.match(await page.locator('[data-live-feedback]').textContent(),/ready/i);await page.locator('[data-capture]').click();for(const[field,value]of Object.entries({clubSpeed:102,spinLoft:45}))await setRange(page,field,value);await page.locator('[data-capture]').click();await page.locator('[data-open-compare]').click();assert.match(await page.locator('.speed-transfer__compare-grid').textContent(),/6\.00 mph.*20\.00°.*0\.080.*0\.00 mph/s);await page.locator('[data-inference="ball-speed-alone-does-not-reveal-delivery"]').click();await page.locator('[data-submit-transfer]').click();assert.equal((await page.locator('[data-result-status]').textContent()).trim(),'Transfer understood');let stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('strikearc.academy.v1')));const state=stored.experiences['speed-transfer'],evidence=state.evidence.liveTransferEvidence;assert.equal(stored.xp,140,JSON.stringify({xp:stored.xp,status:state.status,acceptedAttemptId:state.acceptedAttemptId,rewardLedger:stored.rewardLedger,lastResult:state.evidence.speedTransfer?.lastResult}));assert.equal(state.status,'mastered');assert.equal(Object.values(stored.rewardLedger).filter(item=>item.experienceId==='speed-transfer').length,1);assert.equal(evidence.clubSpeedGap,6);assert.equal(evidence.spinLoftGap,20);assert.ok(evidence.smashGap>=.06);assert.equal(evidence.ballSpeedGap,0);assert.equal(evidence.unclamped,true);assert.equal(evidence.comparePassed,true);assert.equal(evidence.inferencePassed,true);await page.reload({waitUntil:'networkidle'});stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('strikearc.academy.v1')));assert.equal(stored.xp,140);assert.deepEqual(errors,[]);await context.close();});

test('both target viewports keep ordered equation accessible targets and reduced-motion parity',async()=>{for(const viewport of[{width:430,height:932},{width:375,height:812}]){const{context,page,errors}=await open('#/experience/speed-transfer',viewport,null,'reduce');const audit=await page.evaluate(()=>({width:document.documentElement.scrollWidth,client:document.documentElement.clientWidth,equation:document.querySelector('.speed-transfer__ledger figcaption')?.textContent,min:Math.min(...[...document.querySelectorAll('#speedTransferExperience button')].filter(element=>element.offsetParent).map(element=>element.getBoundingClientRect().height)),animation:getComputedStyle(document.querySelector('.speed-transfer__pulse')).animationName}));assert.ok(audit.width<=audit.client+1);assert.equal(audit.equation.trim(),'102.00 mph × 1.280 = 130.56 mph');assert.ok(audit.min>=44);assert.equal(audit.animation,'none');assert.deepEqual(errors,[]);await context.close();}});
