import test from'node:test';import assert from'node:assert/strict';import{createServer}from'node:http';import{createRequire}from'node:module';import{readFile}from'node:fs';import{dirname,extname,resolve,sep}from'node:path';import{fileURLToPath}from'node:url';import{createAcademySeed}from'../academy-store.js';
const require=createRequire(import.meta.url),{chromium,webkit}=require('../tools/node_modules/playwright-core'),ROOT=resolve(dirname(fileURLToPath(import.meta.url)),'..'),WEBKIT=process.env.FG_ENGINE==='webkit'||process.argv.includes('--project=webkit'),mime=file=>({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.woff2':'font/woff2'}[extname(file)]||'application/octet-stream');let server,browser,baseUrl;
test.before(async()=>{server=createServer((request,response)=>{const path=decodeURIComponent(new URL(request.url,'http://x').pathname).replace(/^\/+/, '')||'index.html',file=resolve(ROOT,path),prefix=`${ROOT}${sep}`.toLowerCase();if(!`${file}${sep}`.toLowerCase().startsWith(prefix)){response.writeHead(403).end();return;}readFile(file,(error,data)=>{if(error){response.writeHead(404).end();return;}response.writeHead(200,{'Content-Type':mime(file),'Cache-Control':'no-store'});response.end(data);});});await new Promise((ok,fail)=>{server.once('error',fail);server.listen(0,'127.0.0.1',ok);});baseUrl=`http://127.0.0.1:${server.address().port}`;browser=WEBKIT?await webkit.launch({headless:true}):await chromium.launch({channel:'msedge',headless:true}).catch(()=>chromium.launch({channel:'chrome',headless:true}));});
test.after(async()=>{await browser?.close();await new Promise(ok=>server?.close(ok));});
function master(seed,id){const state=seed.experiences[id];state.status='mastered';state.acceptedAttemptId=`seed:${id}`;state.masteredAt='2026-07-15T10:00:00Z';state.evidence.knowledgeBestCorrect=5;state.evidence.knowledgeTotal=5;state.evidence.liveTransferPassed=true;state.evidence.liveTransferEvidence={seed:true};return seed;}
function prerequisites(){const seed=createAcademySeed();master(seed,'backspin');master(seed,'delivered-loft-launch');return seed;}
function masterySeed({xp=0,grandfather=false}={}){const seed=createAcademySeed();seed.xp=xp;master(seed,'backspin');if(!grandfather)master(seed,'delivered-loft-launch');const state=seed.experiences['flight-height-descent'];state.surface=4;state.unlockedSurfaces=[0,1,2,3,4];state.startedAt='2026-07-15T10:00:00Z';return seed;}
async function open(hash='#/experience/flight-height-descent',viewport={width:430,height:932},seed=null,reducedMotion='no-preference'){const context=await browser.newContext({viewport,deviceScaleFactor:1,reducedMotion}),page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(`pageerror: ${error.message}`));page.on('console',message=>{if(message.type()==='error')errors.push(`console: ${message.text()}`);});if(seed)await page.addInitScript(value=>{if(!localStorage.getItem('strikearc.academy.v1'))localStorage.setItem('strikearc.academy.v1',JSON.stringify(value));},seed);await page.goto(`${baseUrl}/academy.html${hash}`,{waitUntil:'networkidle'});return{context,page,errors};}
const setRange=(page,field,value)=>page.locator(`[data-live-field="${field}"]`).evaluate((element,next)=>{element.value=String(next);element.dispatchEvent(new Event('input',{bubbles:true}));},value);
async function answerMastery(page,answers=[0,0,0,0]){for(let index=0;index<4;index++){await page.locator(`[data-mastery-answer="${answers[index]}"]`).click();await page.locator('[data-action="next"]').click();}}

test('preview and Apex/Landing legacy aliases use one native profile renderer',async()=>{const{context,page,errors}=await open();assert.equal(await page.locator('#flightHeightDescentExperience').count(),1);assert.equal((await page.locator('h1').textContent()).trim(),'Same peak. Different return.');assert.match(await page.locator('.low-point__prereq').textContent(),/PREVIEW/);assert.equal(await page.locator('[data-schematic="true"]').count(),1);assert.match(await page.locator('.flight-height__boundaries').textContent(),/BACKSPIN RPM.*NOT USED.*LANDING ANGLE ≠ STOPPING DISTANCE/s);await page.evaluate(()=>location.hash='#/lesson/apex');await page.locator('[data-sheet-title]').filter({hasText:'Apex'}).waitFor();await page.locator('[data-sheet-close]').click();await page.evaluate(()=>location.hash='#/lesson/landing-angle');await page.locator('[data-sheet-title]').filter({hasText:'Landing Angle'}).waitFor();assert.deepEqual(errors,[]);await context.close();});

test('S0–S3 prove Apex inputs Landing paths clamp and model boundaries',async()=>{const{context,page,errors}=await open('#/experience/flight-height-descent',{width:430,height:932},prerequisites(),'reduce');const lesson=page.locator('#flightHeightDescentExperience');await lesson.locator('[data-primary]').click();for(const[mode,count]of[['launch',3],['speed',3],['reference',1],['separate',2]]){await lesson.locator(`[data-lab-mode="${mode}"]`).click();for(let index=0;index<count;index++)await lesson.locator(`[data-lab-fixture="${index}"]`).click();await lesson.locator('[data-lab-answer="0"]').click();}assert.match(await lesson.textContent(),/APEX INPUTS \+ LANDING REFERENCE VERIFIED/);await lesson.locator('[data-action="next"]').click();for(const stage of['ledger','launch','speed','spin','clamp'])await lesson.locator(`[data-decomposition="${stage}"]`).click();assert.match(await lesson.locator('.flight-height__ledger').textContent(),/LANDING RAW.*60\.608°.*DISPLAY.*60\.000°.*CEILING/s);await lesson.locator('[data-action="next"]').click();for(let index=0;index<5;index++){await lesson.locator('[data-myth-answer="1"]').click();await lesson.locator('[data-action="next"]').click();}assert.equal(await lesson.getAttribute('data-surface'),'4');const metrics=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,min:Math.min(...[...document.querySelectorAll('#flightHeightDescentExperience button,#flightHeightDescentExperience input')].filter(element=>element.offsetParent).map(element=>element.getBoundingClientRect().height))}));assert.equal(metrics.overflow,false);assert.ok(metrics.min>=44);assert.deepEqual(errors,[]);await context.close();});

test('four knowledge answers without the live same-Apex pair remain Practiced',async()=>{const{context,page,errors}=await open('#/experience/flight-height-descent/surface/4',{width:430,height:932},masterySeed({xp:20}));await answerMastery(page);await page.locator('[data-finish]').click();assert.match(await page.locator('[data-result-status]').textContent(),/needs repair/);const stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('strikearc.academy.v1')));assert.equal(stored.xp,20);assert.equal(stored.experiences['flight-height-descent'].status,'practiced');assert.equal(stored.experiences['flight-height-descent'].evidence.knowledgeBestCorrect,4);assert.deepEqual(errors,[]);await context.close();});

test('grandfathered Backspin can build raw same-Apex pair and earns one canonical reward',async()=>{const seed=masterySeed({xp:20,grandfather:true}),backspinId=seed.experiences.backspin.acceptedAttemptId,{context,page,errors}=await open('#/experience/flight-height-descent/surface/4',{width:375,height:812},seed);await answerMastery(page);for(const[field,value]of Object.entries({dynamicLoft:25,attackAngle:-3,clubSpeed:105}))await setRange(page,field,value);assert.match(await page.locator('[data-live-feedback]').textContent(),/gate ready/i);await page.locator('[data-capture]').click();assert.match(await page.locator('.low-point__captures').textContent(),/31\.490 YD · 48\.440°/);for(const[field,value]of Object.entries({dynamicLoft:31,attackAngle:-7,clubSpeed:85}))await setRange(page,field,value);await page.locator('[data-capture]').click();assert.equal((await page.locator('[data-result-status]').textContent()).trim(),'You separated peak height from return angle.');let stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('strikearc.academy.v1')));assert.deepEqual({xp:stored.xp,status:stored.experiences['flight-height-descent'].status,acceptedAttemptId:stored.experiences['flight-height-descent'].acceptedAttemptId,ledger:Object.values(stored.rewardLedger).filter(item=>item.experienceId==='flight-height-descent').length},{xp:140,status:'mastered',acceptedAttemptId:stored.experiences['flight-height-descent'].acceptedAttemptId,ledger:1});assert.equal(stored.experiences.backspin.acceptedAttemptId,backspinId);const evidence=stored.experiences['flight-height-descent'].evidence.liveTransferEvidence;assert.ok(evidence.landingGap>=6);assert.ok(evidence.spinLoftGap>=8);assert.equal(evidence.differentSpeed,true);assert.equal(evidence.unclamped,true);await page.reload({waitUntil:'networkidle'});stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('strikearc.academy.v1')));assert.equal(stored.xp,140);assert.deepEqual(errors,[]);await context.close();});

test('both target viewports keep numeric profile truth keyboard targets and reduced-motion parity',async()=>{for(const viewport of[{width:430,height:932},{width:375,height:812}]){const{context,page,errors}=await open('#/experience/flight-height-descent',viewport,prerequisites(),'reduce');await page.locator('.flight-height__profile[data-schematic="true"] svg').waitFor();const audit=await page.evaluate(()=>({width:document.documentElement.scrollWidth,client:document.documentElement.clientWidth,profile:document.querySelector('.flight-height__profile')?.getAttribute('data-schematic'),aria:document.querySelector('.flight-height__profile svg')?.getAttribute('aria-label'),min:Math.min(...[...document.querySelectorAll('#flightHeightDescentExperience button')].filter(element=>element.offsetParent).map(element=>element.getBoundingClientRect().height))}));assert.ok(audit.width<=audit.client+1);assert.equal(audit.profile,'true');assert.match(audit.aria,/Apex .* yards.*Landing .* degrees down.*equal elevation/i);assert.ok(audit.min>=44);assert.deepEqual(errors,[]);await context.close();}});
