import test from 'node:test';import assert from 'node:assert/strict';
import {solveFlight} from '../impact-flight.js';import {composeCarrySide,evaluateCarrySideTransfer,solveCarrySideState} from '../academy-carry-side-model.js';
const fixtures=[[0,0],[2,4],[-2,-4],[1,1],[2,-2],[0,4],[3,3]];
test('seven Carry Side fixtures preserve engine offline and raw signed decomposition',()=>{for(const[faceAngle,clubPath]of fixtures){const state=solveCarrySideState({faceAngle,clubPath}),flight=solveFlight({faceAngle,clubPath,dynamicLoft:30,attackAngle:-3,clubSpeed:90,club:'7iron'});assert.equal(state.carrySide,flight.offline);assert.ok(Math.abs(state.startSide-state.carry*Math.sin(state.launchDirection*Math.PI/180))<1e-9);assert.ok(Math.abs(state.startSide+state.curve-state.carrySide)<1e-9);}});
test('target-return and same-start fixtures retain exact engine signs and precision',()=>{const a=solveCarrySideState({faceAngle:2,clubPath:4}),b=solveCarrySideState({faceAngle:-2,clubPath:-4});assert.ok(Math.abs(a.startSide-7.519984575564661)<1e-9);assert.ok(Math.abs(a.curve+7.430444335318268)<1e-9);assert.ok(Math.abs(a.carrySide-.08954024024639295)<1e-9);assert.equal(b.startSide,-a.startSide);assert.equal(b.curve,-a.curve);assert.equal(b.carrySide,-a.carrySide);const same=[[1,1],[2,-2],[0,4]].map(([faceAngle,clubPath])=>solveCarrySideState({faceAngle,clubPath}));assert.ok(same.every(item=>Math.abs(item.startSide-3.0087957475339118)<1e-9));});
test('outcome composer is isolated, signed and never masquerades as an engine solve',()=>{const state=composeCarrySide({launchDirection:2.5,curve:-7.430444335318268,carry:172.4});assert.equal(state.mode,'outcome-level-composer');assert.ok(state.startSide>0);assert.ok(state.carrySide>0&&state.carrySide<.1);assert.throws(()=>composeCarrySide({launchDirection:5,curve:0}),RangeError);});
test('two-flight gate accepts verified right-start/left-curve then mirrored state',()=>{const result=evaluateCarrySideTransfer({stateAInput:{faceAngle:2,clubPath:4},stateBInput:{faceAngle:-2,clubPath:-4},stateAInteracted:true,stateBInteracted:true});assert.equal(result.passed,true);assert.equal(result.stateAPassed,true);assert.equal(result.stateBPassed,true);});
test('gate rejects each raw threshold, duplicate, interaction and preset near miss',()=>{const base={stateAInput:{faceAngle:2,clubPath:4},stateBInput:{faceAngle:-2,clubPath:-4},stateAInteracted:true,stateBInteracted:true};assert.equal(evaluateCarrySideTransfer({...base,stateAInput:{faceAngle:1,clubPath:2}}).stateAPassed,false);assert.equal(evaluateCarrySideTransfer({...base,stateBInput:{faceAngle:-1,clubPath:-2}}).stateBPassed,false);assert.equal(evaluateCarrySideTransfer({...base,stateBInput:{faceAngle:2,clubPath:4}}).distinct,false);assert.equal(evaluateCarrySideTransfer({...base,stateAInteracted:false}).passed,false);assert.equal(evaluateCarrySideTransfer({...base,presetInjected:true}).passed,false);assert.equal(evaluateCarrySideTransfer({...base,tolerance:.08}).stateAPassed,false);});
test('invalid inputs fail closed and negative zero is normalized',()=>{assert.throws(()=>solveCarrySideState({faceAngle:7,clubPath:0}),RangeError);assert.equal(evaluateCarrySideTransfer({}).passed,false);assert.equal(Object.is(solveCarrySideState({faceAngle:0,clubPath:0}).carrySide,-0),false);});
